# Generated by Django 5.1.5 on 2025-02-01 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="question_be",
            new_name="question_bn",
        ),
    ]
