# Generated by Django 5.1.5 on 2025-02-01 17:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0002_rename_question_be_faq_question_bn"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer_bn",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_hi",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(),
        ),
    ]
